theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
  - uploadimage
  - emotions
  - advhr
  - ltr
  - rtl
  - media
  - preview
  - styleprops
  - cite
  - ins
  - del
  - abbr
  - acronym

plugins:
  - table
  - fullscreen
  - uploadimage
  - advimage
  - emotions
  - advhr
  - advlink
  - advlist
  - autolink
  - autoresize
  - contextmenu
  - directionality
  - fullscreen
  - media
  - preview
  - style
  - table
  - wordcount
  - xhtmlxtras

language:
  - ru

fullscreen_new_window:
  - true
fullscreen_settings:
  theme_advanced_path_location:
    - top
plugin_preview_width:
  - 1000
plugin_preview_height:
  - 1000
